



# create user
###
POST http://localhost:3000/api/v1/auth/register HTTP/1.1
content-type: application/json
# Authorization: Bearer 

{
   "name":"Rozey kaziibwe",
  "email":"afli@gmail.com",
  "password":"123456",
  "phone":"0785557587",
  "role":"user"

}
###


# create user
###
POST http://localhost:3000/api/v1/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWRiYzk3ZjZhNDljZWM5ZDFlZjZkZSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTYwMDEwMiwiZXhwIjoxNzM5NjAxOTAyfQ.Av8eidep70KQ10SY9GZmjayHqEByysp5QEYpUofnbkI

{
   "name":"Rozey kaziibwe",
  "email":"aine@gmail.com",
  "password":"123456",
  "phone":"0785557587",
  "role":"user",
  "company_id":"67ac71d52103cc38e19928f7"

}
###


###
# api to get all users
GET http://localhost:3000/api/v1/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWM3MWQ1MjEwM2NjMzhlMTk5MjhmOSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTUxNzUwOCwiZXhwIjoxNzM5NTE5MzA4fQ.kn5c31oVl5RuubzvPHEJO0tELciX0jqdZtc8lz2H7GE

###


###
# api to get single users
GET http://localhost:3000/api/v1/users/67ab41f7995d9e1edc0fc1bb HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWM3MWQ1MjEwM2NjMzhlMTk5MjhmOSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTUxNzUwOCwiZXhwIjoxNzM5NTE5MzA4fQ.kn5c31oVl5RuubzvPHEJO0tELciX0jqdZtc8lz2H7GE
###




#  coleb and victor
###
POST http://localhost:3000/api/v1/auth/login HTTP/1.1
content-type: application/json
# Authorization: Bearer 

{
  "email":"bobii@gmail.com",
  "password":"123456"
}
###



###
# get new access token and refresh token
POST http://localhost:3000/api/v1/auth/token HTTP/1.1
content-type: application/json
# Authorization: Bearer 

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWM3MWQ1MjEwM2NjMzhlMTk5MjhmOSIsImlhdCI6MTczOTQzODc4Nn0.dVP_KkIRzzJ3s5lvOv5A4-opFH4pOEX0cwlJPd0sTtU"
}
###


POST http://localhost:3000/api/v1/auth/logout HTTP/1.1
content-type: application/json
# Authorization: Bearer 

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWM3MWQ1MjEwM2NjMzhlMTk5MjhmOSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTQzOTA3MSwiZXhwIjoxNzM5NDQwODcxfQ.kLUeWL4RW9YtC6ZGSPprE94IhzdGqkdXk0JwhruwmhI"
}
###




###
POST http://localhost:3000/api/v1/company HTTP/1.1
content-type: application/json
# Authorization: Bearer 

{
  
  "companyname":"Tubayo  ",
  "companyemail":"bobii@gmail.com ",
  "companylocation":"Nakawa ",
  "industry":"software enterprise",
  "name":"Ssendegeya Albert",
  "email":"bobii@gmail.com",
  "password":"123456",
  "phone":"0786567850",
  "role":"admin"

  
}
###

# get single company data
GET http://localhost:3000/api/v1/company/67ac71d52103cc38e19928f7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWRiYzk3ZjZhNDljZWM5ZDFlZjZkZSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTYwMDEwMiwiZXhwIjoxNzM5NjAxOTAyfQ.Av8eidep70KQ10SY9GZmjayHqEByysp5QEYpUofnbkI

###


# get single company data
GET http://localhost:3000/api/v1/company/67ac71d52103cc38e19928f7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWM3MWQ1MjEwM2NjMzhlMTk5MjhmOSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTQzOTM4MywiZXhwIjoxNzM5NDQxMTgzfQ.7hjqlw9snnExy1_j5AuvhHe66zdiksvM-uChCSYrgBU

###

###
# get all companies

GET https://multi-agents-production.up.railway.app/api/v1/company HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWRiN2I2NTI1ODBmMTQ2Y2VlOTI0MCIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTUzNTk4MywiZXhwIjoxNzM5NTM3NzgzfQ.j2mju35ixyFpIreu75DuSS36_NDV2rwZwZkO4AczfSs

###
PUT http://localhost:3000/api/v1/company/67adf1eef3b7324d42e65642 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWM3MWQ1MjEwM2NjMzhlMTk5MjhmOSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTQzOTM4MywiZXhwIjoxNzM5NDQxMTgzfQ.7hjqlw9snnExy1_j5AuvhHe66zdiksvM-uChCSYrgBU

{
  
  "companyname":"Tubayo  ",
  "companyemail":"alfredo@gmail.com ",
  "companylocation":"Nakawa ",
  "industry":"software skdf"


  
}
###



###
# api to create agents
POST http://localhost:3000/api/v1/agents HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWM3MWQ1MjEwM2NjMzhlMTk5MjhmOSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTM2ODQ4MCwiZXhwIjoxNzM5MzcwMjgwfQ.Ok1N_DbcKPVwFAmF--FtWx849qUCm_PGR_eK02IRQXQ

{

  "name":"Najod  3 ",
  "description":"thant is to help impove marketing 24/7 support ",
  "title":"this to take it to the next level ",
  "status":"update"
}
###
















###
# api to get all agents
GET https://multi-agents-production.up.railway.app/api/v1/agents HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWRiN2I2NTI1ODBmMTQ2Y2VlOTI0MCIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTUyMjI5MywiZXhwIjoxNzM5NTI0MDkzfQ.r2qaCsXXbmaOBIQ77aCuFRPaun-vJcEqaLHfaD95_VI

###


###
# api to get single agent
GET http://localhost:3000/api/v1/agents/67aca2751cdcc2e11a6b217d HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWRiYzk3ZjZhNDljZWM5ZDFlZjZkZSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTUzODEyNiwiZXhwIjoxNzM5NTM5OTI2fQ.ONHQqpHrPLSYaeI20hHtumBThKdB6QEc57Zs5aswZW0

###




###
# api to update agents
PUT http://localhost:3000/api/v1/agents/67aca2751cdcc2e11a6b217d HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWM3MWQ1MjEwM2NjMzhlMTk5MjhmOSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTQzMzY4OSwiZXhwIjoxNzM5NDM1NDg5fQ.hJTeLHXHowQfYnotPaP7P3AjdrNqPgQXyNUxz0c45OU

{

  "name":"tiko 45krjt 3 ",
  "description":"we is to help impove marketing 24/7 support ",
  "title":"this to take it to the next level ",
  "status":"submited"
}
###


###
POST http://localhost:3000/api/v1/purchasedagents HTTP/1.1
content-type: application/json 

{
  
  "companyname":"Tubayo  ",
  "companyemail":"rayo1@gmail.com ",
  "companylocation":"Nakawa ",
  "industry":"software enterprise",
  "name":"Ssendegeya Albert",
  "email":"rayo1@gmail.com",
  "password":"123456",
  "phone":"0786567850",
  "role":"admin",
  "plan" :"enterprise", 
  "amount":"5000",      
  "period":90,
  "agent_id":"67aca2751cdcc2e11a6b217d"
  
}
###



###
POST http://localhost:3000/api/v1/purchasedagents/withacount HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWRiYzk3ZjZhNDljZWM5ZDFlZjZkZSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTUzODEyNiwiZXhwIjoxNzM5NTM5OTI2fQ.ONHQqpHrPLSYaeI20hHtumBThKdB6QEc57Zs5aswZW0


{
  "company_id":"67ac71d52103cc38e19928f7",
  "plan" :"enterprise", 
  "amount":"5000",      
  "period":90,
  "agent_id":"67aca2751cdcc2e11a6b217d"
}
###


GET http://localhost:3000/api/v1/purchasedagents/67ae5ee1c8bb70ec199f6bc3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWRiYzk3ZjZhNDljZWM5ZDFlZjZkZSIsIm5hbWUiOiJTc2VuZGVnZXlhIEFsYmVydCIsImlhdCI6MTczOTU0MDA0NywiZXhwIjoxNzM5NTQxODQ3fQ.Sm1za8VG6Mpl5cnIlc3Tmfmu2VlulIQ69UDFiRxbAlk

###


  